Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8081
    ubuntu.vm.provision "shell",
    inline:
    "apt install -y nginx
     service nginx start
     service nginx status"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.provision "shell",
    inline:
    "cd /vagrant
     ./Dockerfile.sh"
  end
end

