Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "forwarded_port", guest: 8080, host: 443
    ubuntu.vm.provision "shell",
    inline:
    "ls -a /vagrant
     cd /vagrant
     ./lenchuk6.sh"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/6"
    centos.vm.provision "shell",
    inline:
    "yum install -y epel-release
     yum install -y nginx
     service nginx start
     service nginx status"
  end
end

