Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.network "forwarded_port", guest: 3306, host: 8081
    ubuntu.vm.provision "shell",
    inline:
    "apt install -y mysql-server"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.provision "shell",
    inline:
    "yum install -y git
     git --version
     git clone https://github.com/dimalenchuk/bilet8test
     cd bilet8test
     ls -a
     touch maintainer.md
     ls -a"
  end
end

