Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 80
    ubuntu.vm.provision "shell",
    inline:
    "ls -a /vagrant
     cd /vagrant
     ./lenchuk5.sh"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.provision "shell",
    inline:
    "yum update -y
     yum install -y httpd
     service httpd start
     service httpd status"
  end
end

